### PR TITLE
Add TestHttpClient.request API

### LINKED ISSUE #826: TestHttpClient should provide method for executing a pre-configured request
Support dynamically configuring the HTTP request method on TestHttpClient via a RequestSpec.
Currently, the TestHttpClient API overwrites the HTTP method with the method type associated with the API method that is called.
We should provide a `request(Action<? super RequestSpec>)` method that allows an arbitrary request to be executed from the provided spec.

### PR DESCRIPTION
**Pull request by johnrengelman**
Closes #826.

[Review on Reviewable](https://reviewable.io/reviews/ratpack/ratpack/827)

### CODE REVIEW

**Comment by alkemist** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[ratpack-core/src/test/groovy/ratpack/http/client/HttpClientSmokeSpec.groovy, line 565 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/827#-K2ULKsF4x5pDnNGNvrA)** ([raw file](https://github.com/ratpack/ratpack/blob/44e309d4c79d2a1a92321d7a93b9918d84457c3c/ratpack-core/src/test/groovy/ratpack/http/client/HttpClientSmokeSpec.groovy#L565)):</sup>
Any reason not to use render() here?


---

<sup>**[ratpack-test/src/main/java/ratpack/test/http/TestHttpClient.java, line 306 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/827#-K2UL_et7RtIKlO1I7Eo)** ([raw file](https://github.com/ratpack/ratpack/blob/44e309d4c79d2a1a92321d7a93b9918d84457c3c/ratpack-test/src/main/java/ratpack/test/http/TestHttpClient.java#L306)):</sup>
This reads strangely, and is missing a full stop.


---

<sup>**[ratpack-test/src/main/java/ratpack/test/http/TestHttpClient.java, line 308 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/827#-K2ULev2cKlGuceBjpMm)** ([raw file](https://github.com/ratpack/ratpack/blob/44e309d4c79d2a1a92321d7a93b9918d84457c3c/ratpack-test/src/main/java/ratpack/test/http/TestHttpClient.java#L308)):</sup>
The non-additive characteristic should be explained as a paragraph. We should avoid using multiple sentences here.


---

<sup>**[ratpack-test/src/main/java/ratpack/test/http/TestHttpClient.java, line 316 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/827#-K2ULrexgpv02fYejRyY)** ([raw file](https://github.com/ratpack/ratpack/blob/44e309d4c79d2a1a92321d7a93b9918d84457c3c/ratpack-test/src/main/java/ratpack/test/http/TestHttpClient.java#L316)):</sup>
Same issue here.


---

<sup>**[ratpack-test/src/main/java/ratpack/test/http/TestHttpClient.java, line 318 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/827#-K2ULu-T5Lx-IbpSitrZ)** ([raw file](https://github.com/ratpack/ratpack/blob/44e309d4c79d2a1a92321d7a93b9918d84457c3c/ratpack-test/src/main/java/ratpack/test/http/TestHttpClient.java#L318)):</sup>
we don't use sentences here, so no initial cap and full stop. The phrase is also worded a little bit strangely.


---

<sup>**[ratpack-test/src/main/java/ratpack/test/http/TestHttpClient.java, line 320 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/827#-K2UM3f6snj06BHUufvd)** ([raw file](https://github.com/ratpack/ratpack/blob/44e309d4c79d2a1a92321d7a93b9918d84457c3c/ratpack-test/src/main/java/ratpack/test/http/TestHttpClient.java#L320)):</sup>
don't need a link to the type here


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/827)

**Comment by alkemist** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/827)

**Comment by beckje01** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[ratpack-core/src/test/groovy/ratpack/http/client/HttpClientSmokeSpec.groovy, line 565 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/827#-K2ULKsF4x5pDnNGNvrA)** ([raw file](https://github.com/ratpack/ratpack/blob/44e309d4c79d2a1a92321d7a93b9918d84457c3c/ratpack-core/src/test/groovy/ratpack/http/client/HttpClientSmokeSpec.groovy#L565)):</sup>
If we keep it as response.send it is only testing the httpclient and not depending on rendering which could be effected separably, I think we want to keep the tests with the http client simple so we know where issues come up. 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/827)

**Comment by johnrengelman** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[ratpack-core/src/test/groovy/ratpack/http/client/HttpClientSmokeSpec.groovy, line 565 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/827#-K2ULKsF4x5pDnNGNvrA)** ([raw file](https://github.com/ratpack/ratpack/blob/44e309d4c79d2a1a92321d7a93b9918d84457c3c/ratpack-core/src/test/groovy/ratpack/http/client/HttpClientSmokeSpec.groovy#L565)):</sup>
I was simply following the testing style that was already laid out in this spec. Though I think Jeff has a good point, so I would be inclined to leave it as is.


---

<sup>**[ratpack-test/src/main/java/ratpack/test/http/TestHttpClient.java, line 318 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/827#-K2ULu-T5Lx-IbpSitrZ)** ([raw file](https://github.com/ratpack/ratpack/blob/44e309d4c79d2a1a92321d7a93b9918d84457c3c/ratpack-test/src/main/java/ratpack/test/http/TestHttpClient.java#L318)):</sup>
I just c&p'd the javadoc styling that was already in use in this class (i.e https://github.com/ratpack/ratpack/blob/master/ratpack-test/src/main/java/ratpack/test/http/TestHttpClient.java#L176-L189). Do you want this fixed throughout the javadoc?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/827)

**Comment by alkemist** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[ratpack-test/src/main/java/ratpack/test/http/TestHttpClient.java, line 318 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/827#-K2ULu-T5Lx-IbpSitrZ)** ([raw file](https://github.com/ratpack/ratpack/blob/44e309d4c79d2a1a92321d7a93b9918d84457c3c/ratpack-test/src/main/java/ratpack/test/http/TestHttpClient.java#L318)):</sup>
Yes please.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/827)

**Comment by alkemist** [comment]
Review status: 1 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[ratpack-core/src/main/java/ratpack/http/HttpUrlBuilder.java, line 188 \[r3\]](https://reviewable.io:443/reviews/ratpack/ratpack/827#-K57ci5Z90k57sFbe_fs:-K57ci5Z90k57sFbe_ft:1983102540) ([raw file](https://github.com/ratpack/ratpack/blob/51386de676a1aa82fdd94ccce1f86399ee8ec90a/ratpack-core/src/main/java/ratpack/http/HttpUrlBuilder.java#L188)):*
Why do we need this method?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/827)*

**Comment by alkemist** [comment]
Reviewed 1 of 2 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/827)*

**Comment by alkemist** [comment]
Reviewed 4 of 8 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/827)*

**Comment by alkemist** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ratpack-core/src/test/groovy/ratpack/http/client/HttpClientSmokeSpec.groovy, line 565 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/827#-K2ULKsF4x5pDnNGNvrA:-K5HdyV3uRtOLXa83JGr:-864509007) ([raw file](https://github.com/ratpack/ratpack/blob/44e309d4c79d2a1a92321d7a93b9918d84457c3c/ratpack-core/src/test/groovy/ratpack/http/client/HttpClientSmokeSpec.groovy#L565)):*
Resolved.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/827)*

**Pull request merged**
