### PR TITLE
Allow ordering services.

### PR DESCRIPTION
**Pull request by alkemist**
Solution for #883.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/ratpack/ratpack/935)

### CODE REVIEW

**Comment by alkemist** [comment]
@ratpack/committers this is ready for review. I think we should improve the cycle error message as a separate change.

I think we should also do a deprecate/move for `ratpack.server.Service` to `ratpack.service.Service` as a separate change.

**Comment by beckje01** [comment]
While I really like the direction this is going I wonder if we need to provide a default way of starting services synchronously  with the old ordering and allow this preferred way of starting services to be opted into. The concern I have is this will be a non obvious breaking change for some applications that are depending on the ordered sync starting of services.

As for the deprecation thats something that will be deprecated then removed in 2.0 right?

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ratpack-core/src/main/java/ratpack/exec/Operation.java, line 129 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/935#-KCa6BE2pHiEUO-0Tf-W:-KCa6BE2pHiEUO-0Tf-X:-485787105) ([raw file](https://github.com/ratpack/ratpack/blob/3de2ebaed312f8b29be4dd59780077e4b7def246/ratpack-core/src/main/java/ratpack/exec/Operation.java#L129)):*
Where does this get used?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/935#-:-KCa4qybtHaTOykBm0ox:842827776)*

**Comment by alkemist** [comment]
Regarding the breaking change, I think we should just do it and document it clearly in the release notes. It's a clearly superior mechanism and the current behaviour isn't really safe (e.g. adding a new binding can change service ordering in unpredictable ways). So, the benefit here outweighs the cost and adapting for the change will be trivial for most users (e.g. just add some @DependsOn).

As for the deprecations, yeah removal for 2.0.

---

Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[ratpack-core/src/main/java/ratpack/exec/Operation.java, line 129 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/935#-KCa6BE2pHiEUO-0Tf-W:-KChkpWhXl-LPb6m4PHn:1855392001) ([raw file](https://github.com/ratpack/ratpack/blob/3de2ebaed312f8b29be4dd59780077e4b7def246/ratpack-core/src/main/java/ratpack/exec/Operation.java#L129)):*
Good catch. I have removed it. It was used in an earlier version of ServicesGraph.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/935#-:-KChk7tOW-oyw1-Ex06I:-487814179)*

**Comment by beckje01** [comment]
The main oddity for this release is it won't throw any errors at boot time from ratpack in particular it just changes the order that things load which can cause more subtle bugs. It seems like we can just document would it be better if we added the new  `ratpack.service.Service`and allowed only it to use the DependsOn async semantics and leave the deprecated class around on the old serial way of doing things. User can opt into the new better way of doing services and by doing that they move off the deprecated class and way of thinking about starting the application.

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/935#-:-KCqQmRwJFb0DJbfR_3G:292413033)*

**Comment by alkemist** [comment]
That's a really good idea. Let's do that.

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/935#-:-KCr6NilK6pgAtCBQiFy:82009129)*

**Pull request merged**
