### PR TITLE
Rx2 module

### PR DESCRIPTION
**Pull request by johnrengelman**
Replaces https://github.com/ratpack/ratpack/pull/1218

---
This change is [Reviewable](https://reviewable.io/reviews/ratpack/ratpack/1305)

### CODE REVIEW

**Comment by johnrengelman** [comment]
This is pretty close to being ready.
I had to move the javadoc testing code to `ratpack-test-internal` and implement a class in each project to avoid conflicting dependencies in `ratpack-manual` when it ran the javadocs tests.

Things that still need to happen:
- [ ] Figure out how to add a javadoc test to `ratpack-groovy-test`. This in cyclical with `ratpack-test-internal`. Maybe the javadoc test code needs to move to its own module.
- [ ] Add `ratpack-rx2` to the list of `apiModules`. This will still cause a dependency conflict in `ratpack-manual`, but it might auto-resolve and be ok as long as we don't try to add manual pages for both `ratpack-rx` and `ratpack-rx2`.
- [ ] Lost of javadoc in `ratpack-rx2` that needs to be completed.

**Comment by johnrengelman** [comment]
Ok - i think this is ready to be merged as is, and then we can fill in the documentation gaps from there. Thoughts @ratpack/committers ?

**Comment by rhart** [comment]
*[ratpack-rx2/ratpack-rx2.gradle, line 31 at r6](https://reviewable.io:443/reviews/ratpack/ratpack/1305#-L20ApRT5e_tSb1mwf5Q:-L20ApRT5e_tSb1mwf5R:bjs6cto) ([raw file](https://github.com/ratpack/ratpack/blob/01491c0f23d4309f5d98768048c407eac3a490a8/ratpack-rx2/ratpack-rx2.gradle#L31)):*
> ```Gradle
> 
> configurations.all*.resolutionStrategy {
>       force "org.reactivestreams:reactive-streams:1.0.0.final", "org.reactivestreams:reactive-streams:1.0.2"
> ```

We could move to 1.0.2 I guess.  Or at least create an issue to do so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1305)*

**Comment by rhart** [comment]
*[ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java, line 146 at r6](https://reviewable.io:443/reviews/ratpack/ratpack/1305#-L20GI9021nTxDQK24qB:-L20GI9021nTxDQK24qC:bkjyh40) ([raw file](https://github.com/ratpack/ratpack/blob/01491c0f23d4309f5d98768048c407eac3a490a8/ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java#L146)):*
> ```Java
>    * @return an observable for the operation
>    */
>   public static Observable<Void> observe(Operation operation) {
> ```

I'm not sure this method makes sense.  In the more recent versions of RX you are more likely to want to convert an Operation to a Completable than an Observable<Void>.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1305)*

**Comment by rhart** [comment]
*[ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java, line 183 at r6](https://reviewable.io:443/reviews/ratpack/ratpack/1305#-L20I9cjvaD9m4tIjViQ:-L20I9ckSxF795ck9lhO:bduzlw) ([raw file](https://github.com/ratpack/ratpack/blob/01491c0f23d4309f5d98768048c407eac3a490a8/ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java#L183)):*
> ```Java
>    * @return an observable for the promised value
>    */
>   public static <T> Observable<T> observe(Promise<T> promise) {
> ```

I think a return of Single<T> would make more sense here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1305)*

**Comment by rhart** [comment]
*[ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java, line 146 at r6](https://reviewable.io:443/reviews/ratpack/ratpack/1305#-L20GI9021nTxDQK24qB:-L20IZUWb9h-nbcjGZPH:bukfj18) ([raw file](https://github.com/ratpack/ratpack/blob/01491c0f23d4309f5d98768048c407eac3a490a8/ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java#L146)):*
<details><summary><i>Previously, rhart (Rus Hart) wrote…</i></summary><blockquote>

I'm not sure this method makes sense.  In the more recent versions of RX you are more likely to want to convert an Operation to a Completable than an Observable<Void>.
</blockquote></details>

I can see the other methods further down the class.  Personally I think this can just go.  What is the use case for it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1305)*

**Comment by rhart** [comment]
*[ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java, line 183 at r6](https://reviewable.io:443/reviews/ratpack/ratpack/1305#-L20I9cjvaD9m4tIjViQ:-L20IlS_iqrjhrpd7TSE:bukfj18) ([raw file](https://github.com/ratpack/ratpack/blob/01491c0f23d4309f5d98768048c407eac3a490a8/ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java#L183)):*
<details><summary><i>Previously, rhart (Rus Hart) wrote…</i></summary><blockquote>

I think a return of Single<T> would make more sense here.
</blockquote></details>

I can see the other methods further down the class.  Personally I think this can just go.  What is the use case for it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1305)*

**Comment by rhart** [comment]
*[ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java, line 146 at r6](https://reviewable.io:443/reviews/ratpack/ratpack/1305#-L20GI9021nTxDQK24qB:-L20JUdM1avQhtPhaMz-:bowup62) ([raw file](https://github.com/ratpack/ratpack/blob/01491c0f23d4309f5d98768048c407eac3a490a8/ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java#L146)):*
<details><summary><i>Previously, rhart (Rus Hart) wrote…</i></summary><blockquote>

I can see the other methods further down the class.  Personally I think this can just go.  What is the use case for it?
</blockquote></details>

Actually, there is no complete(Operation operation) only from Promise<Void>. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1305)*

**Comment by johnrengelman** [comment]
Review status: 0 of 88 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ratpack-rx2/ratpack-rx2.gradle, line 31 at r6](https://reviewable.io:443/reviews/ratpack/ratpack/1305#-L20ApRT5e_tSb1mwf5Q:-L20SUwywAczt_6X6kb4:bdflhst) ([raw file](https://github.com/ratpack/ratpack/blob/01491c0f23d4309f5d98768048c407eac3a490a8/ratpack-rx2/ratpack-rx2.gradle#L31)):*
<details><summary><i>Previously, rhart (Rus Hart) wrote…</i></summary><blockquote>

We could move to 1.0.2 I guess.  Or at least create an issue to do so.
</blockquote></details>

So I think this is because `ratpack-exec` compiles against reactivestreams. But I didn't want to change it for `ratpack-rx`. The RX2 library pulls in its own copy of reactivestreams. Are you suggesting just upgrade the whole project?

---

*[ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java, line 146 at r6](https://reviewable.io:443/reviews/ratpack/ratpack/1305#-L20GI9021nTxDQK24qB:-L20SrLflxJZmyVTBuB_:b5kl6gj) ([raw file](https://github.com/ratpack/ratpack/blob/01491c0f23d4309f5d98768048c407eac3a490a8/ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java#L146)):*
<details><summary><i>Previously, rhart (Rus Hart) wrote…</i></summary><blockquote>

Actually, there is no complete(Operation operation) only from Promise<Void>. 
</blockquote></details>

I reached out to Dan Maas to see if he wants to address these API questions or if we should just handle them.

---

*[ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java, line 183 at r6](https://reviewable.io:443/reviews/ratpack/ratpack/1305#-L20I9cjvaD9m4tIjViQ:-L20SyudiPjPj3WKm1MP:bd34t5u) ([raw file](https://github.com/ratpack/ratpack/blob/01491c0f23d4309f5d98768048c407eac3a490a8/ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java#L183)):*
<details><summary><i>Previously, rhart (Rus Hart) wrote…</i></summary><blockquote>

I can see the other methods further down the class.  Personally I think this can just go.  What is the use case for it?
</blockquote></details>

Reaching out to Dan Maas about these.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1305)*

**Comment by johnrengelman** [comment]
Review status: 0 of 88 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java, line 146 at r6](https://reviewable.io:443/reviews/ratpack/ratpack/1305#-L20GI9021nTxDQK24qB:-L20T_xiIjX0MkgDzixn:bocdq89) ([raw file](https://github.com/ratpack/ratpack/blob/01491c0f23d4309f5d98768048c407eac3a490a8/ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java#L146)):*
<details><summary><i>Previously, johnrengelman (John Engelman) wrote…</i></summary><blockquote>

I reached out to Dan Maas to see if he wants to address these API questions or if we should just handle them.
</blockquote></details>

I think it would make the most sense for the Ratpack stuff to do the following:
* Operation -> Completable
* Promise -> Single

Any conversion to Observable can happen by calling methods on the resulting values: `operation.complete().toObservable()` and `promise.single().toObservable()`

This would reduce the footprint of Ratpack's exposure to the RX Api.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1305)*

**Comment by rhart** [comment]
*[ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java, line 146 at r6](https://reviewable.io:443/reviews/ratpack/ratpack/1305#-L20GI9021nTxDQK24qB:-L20c-_v6TaKyyBL9rd4:bqog7zb) ([raw file](https://github.com/ratpack/ratpack/blob/01491c0f23d4309f5d98768048c407eac3a490a8/ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java#L146)):*
<details><summary><i>Previously, johnrengelman (John Engelman) wrote…</i></summary><blockquote>

I think it would make the most sense for the Ratpack stuff to do the following:
* Operation -> Completable
* Promise -> Single

Any conversion to Observable can happen by calling methods on the resulting values: `operation.complete().toObservable()` and `promise.single().toObservable()`

This would reduce the footprint of Ratpack's exposure to the RX Api.
</blockquote></details>

Agree.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1305)*

**Comment by rhart** [comment]
*[ratpack-rx2/ratpack-rx2.gradle, line 31 at r6](https://reviewable.io:443/reviews/ratpack/ratpack/1305#-L20ApRT5e_tSb1mwf5Q:-L20cMCdYPhwHvF6YJIF:b-x9u3pv) ([raw file](https://github.com/ratpack/ratpack/blob/01491c0f23d4309f5d98768048c407eac3a490a8/ratpack-rx2/ratpack-rx2.gradle#L31)):*
<details><summary><i>Previously, johnrengelman (John Engelman) wrote…</i></summary><blockquote>

So I think this is because `ratpack-exec` compiles against reactivestreams. But I didn't want to change it for `ratpack-rx`. The RX2 library pulls in its own copy of reactivestreams. Are you suggesting just upgrade the whole project?
</blockquote></details>

Yes, upgrading the whole project.  But maybe under a new issue that reminds to get rid of this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1305)*

**Comment by johnrengelman** [comment]
@rhart I went through and reduced the footprint on this PR. Can you take a look now?
I'm hoping this is good starting point and any future sugar can come later.

**Comment by rhart** [comment]
*[ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java, line 227 at r7](https://reviewable.io:443/reviews/ratpack/ratpack/1305#-L5DtSKDgryQ3u1KJCk2:-L5DtSKEvf2CctBdgCwU:brq15lc) ([raw file](https://github.com/ratpack/ratpack/blob/5d4968f1e61ddd7c2866ffe86dd8522e3b468de5/ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java#L227)):*
> ```Java
>    * @see #promise(Single)
>    */
>   public static <T> Promise<List<T>> promiseAll(Observable<T> observable) throws UnmanagedThreadException {
> ```

Do you think this would be better called `promise`?  So rather than introduce a new operation name just have overloads for `promise`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1305)*

**Comment by rhart** [comment]
*[ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java, line 146 at r6](https://reviewable.io:443/reviews/ratpack/ratpack/1305#-L20GI9021nTxDQK24qB:-L5Dtu7Xsmxk0kRBPUbd:b-drzgz5) ([raw file](https://github.com/ratpack/ratpack/blob/01491c0f23d4309f5d98768048c407eac3a490a8/ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java#L146)):*
<details><summary><i>Previously, rhart (Rus Hart) wrote…</i></summary><blockquote>

Agree.
</blockquote></details>

LGTM, I much prefer this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1305)*

**Comment by rhart** [comment]
*[ratpack-rx2/src/test/groovy/ratpack/rx2/RxHttpClientSpec.groovy, line 40 at r7](https://reviewable.io:443/reviews/ratpack/ratpack/1305#-L5DvczZ8TDOZr_6iIUU:-L5DvczZ8TDOZr_6iIUV:bx99d5) ([raw file](https://github.com/ratpack/ratpack/blob/5d4968f1e61ddd7c2866ffe86dd8522e3b468de5/ratpack-rx2/src/test/groovy/ratpack/rx2/RxHttpClientSpec.groovy#L40)):*
> ```Groovy
>     handlers {
>       get { HttpClient httpClient ->
>         single(httpClient.get(otherAppUrl("foo"))).toFlowable() map({
> ```

Would be nice to use the groovy extension methods in this test to make it easier to read.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1305)*

**Comment by rhart** [comment]
Reviewed 3 of 48 files at r1, 86 of 112 files at r2, 3 of 3 files at r4, 2 of 2 files at r5, 17 of 26 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1305)*

**Comment by johnrengelman** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java, line 227 at r7](https://reviewable.io:443/reviews/ratpack/ratpack/1305#-L5DtSKDgryQ3u1KJCk2:-L5fOm9VHlBHu6lrS2_g:bb4gt2m) ([raw file](https://github.com/ratpack/ratpack/blob/5d4968f1e61ddd7c2866ffe86dd8522e3b468de5/ratpack-rx2/src/main/java/ratpack/rx2/RxRatpack.java#L227)):*
<details><summary><i>Previously, rhart (Rus Hart) wrote…</i></summary><blockquote>

Do you think this would be better called `promise`?  So rather than introduce a new operation name just have overloads for `promise`.
</blockquote></details>

Hmm, i'll need to look at it again but I think I ran into some issues here with the functional interfaces overlapping. 

---

*[ratpack-rx2/src/test/groovy/ratpack/rx2/RxHttpClientSpec.groovy, line 40 at r7](https://reviewable.io:443/reviews/ratpack/ratpack/1305#-L5DvczZ8TDOZr_6iIUU:-L5fOv00xr1brbPNAcx2:b-eqsl6j) ([raw file](https://github.com/ratpack/ratpack/blob/5d4968f1e61ddd7c2866ffe86dd8522e3b468de5/ratpack-rx2/src/test/groovy/ratpack/rx2/RxHttpClientSpec.groovy#L40)):*
<details><summary><i>Previously, rhart (Rus Hart) wrote…</i></summary><blockquote>

Would be nice to use the groovy extension methods in this test to make it easier to read.
</blockquote></details>

Agreed. I'll do that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1305)*

**Pull request closed without merging**
