### PR TITLE
Edited comparison with Vert.x

### PR DESCRIPTION
**Pull request by purplefox**
Hi Luke,

I've tried to come up with a more accurate comparison with Vert.x.

Tbh I disagreed with pretty much everything on the old comparison, so I've pretty much replaced it.

Fyi, there's some "what is vert.x?" info on the (currently WIP) Vert.x 3.0 website: https://vertx.ci.cloudbees.com/view/vert.x-3/job/vert.x3-website/ws/target/site/docs/manual.html

### CODE REVIEW

**Comment by alkemist** [comment]
Hi Tim,

I've decided I'm just going to remove the comparisons section entirely. It was a bit ambitious. They will still be there in the old manual versions, but going forward it's gone. The http://www.ratpack.io/manual/current/intro.html URL will update on the 1st of March.

**Comment by purplefox** [comment]
Luke, do you mean 1st April?

**Comment by alkemist** [comment]
Ha, yeah. I thought we were still in February.

**Comment by purplefox** [comment]
Any chance you could remove the Vert.x part before that? Almost a month seems a long time to push a website change ;)

**Comment by alkemist** [comment]
It's part of the versioned manual, so not until the next release.

**Pull request closed without merging**
