### PR TITLE
Additional dropwizard metrics customizations

### PR DESCRIPTION
**Pull request by drmaas**
Allow default timing handler and interceptor to be disabled via config, and allow for providing custom implementations of the same.

See issue #756

[Review on Reviewable](https://reviewable.io/reviews/ratpack/ratpack/832)

### CODE REVIEW

**Comment by rhart** [comment]
I'm on hols at the mo, will take a look as soon as I get back

**Comment by alkemist** [comment]
@drmaas sorry for the egregious delay.

Do we need the ability for custom implementations of the interceptors? It adds quite a bit of complexity for not much value.

**Comment by drmaas** [comment]
We'd use it at Target.  Not sure if others would use it, or would want simply disable the defaults. Our main use case is disabling the defaults. Overriding defaults is of secondary import.

Agreed it shouldn't be hard to just add handlers and interceptors independently.

**Comment by alkemist** [comment]
Seems that there's not that much value in the common infrastructure provided by the base classes, that isn't easily done in a custom impl.

Would you mind removing that part of the PR. The rest looks good to merge.

Thanks for your patience.

**Comment by drmaas** [comment]
The latest build failure seems unrelated to this PR, unless I'm missing something.

**Comment by rhart** [comment]
Thanks @drmaas.  I'll do a manual merge on this and sort any build issues out.  

Thanks again for the PR and your patience in getting it merged!

**Pull request merged**
