### PR TITLE
Support base dir relative paths to config files with ServerConfigBuilder

### PR DESCRIPTION
**Pull request by alkemist**
Addresses #725

[Review on Reviewable](https://reviewable.io/reviews/ratpack/ratpack/758)

### CODE REVIEW

**Comment by danhyun** [comment]
<sup>**[ratpack-core/src/main/java/ratpack/config/internal/module/ServerConfigDataDeserializer.java, line 60 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/758#-JwtR8IzSBS8b0xdXG84)** ([raw file](https://github.com/ratpack/ratpack/blob/af8e6e60c82edf7862805fe9ebb0ff3e78aa9fbb/ratpack-core/src/main/java/ratpack/config/internal/module/ServerConfigDataDeserializer.java#L60)):</sup>
I particularly like this

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/758)

**Comment by johnrengelman** [comment]
Reviewed 36 of 37 files at r1.
Review status: 36 of 37 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[ratpack-core/src/test/groovy/ratpack/server/ServerConfigBuilderEnvVarsSpec.groovy, line 34 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/758#-JwvscsVojL6pDsGLsrI)** ([raw file](https://github.com/ratpack/ratpack/blob/af8e6e60c82edf7862805fe9ebb0ff3e78aa9fbb/ratpack-core/src/test/groovy/ratpack/server/ServerConfigBuilderEnvVarsSpec.groovy#L34)):</sup>
So, we all 'server' options to be both scoped and unscoped? (i.e. `RATPACK_PORT` and `RATPACK_SERVER__PORT` will set the same value? Just want to make sure on this because it seems you've updated a bunch of tests to use the full namespace (`RATPACK_SERVER__PORT`) but the non-namespaced still works (as shown by this test).

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/758)

**Comment by johnrengelman** [comment]
Reviewed 1 of 37 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/758)

**Comment by alkemist** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[ratpack-core/src/test/groovy/ratpack/server/ServerConfigBuilderEnvVarsSpec.groovy, line 34 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/758#-JwvscsVojL6pDsGLsrI)** ([raw file](https://github.com/ratpack/ratpack/blob/af8e6e60c82edf7862805fe9ebb0ff3e78aa9fbb/ratpack-core/src/test/groovy/ratpack/server/ServerConfigBuilderEnvVarsSpec.groovy#L34)):</sup>
This is a bit of relic from the pre config days. RATPACK_PORT (and DEVELOPMENT and PUBLIC_ADDRESS) work without calling .env(). Whether this still makes sense or not is a separate question.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/758)

**Pull request merged**
