### PR TITLE
Improve Gradle build cacheability

### PR DESCRIPTION
**Pull request by jprinet**
This change is [Reviewable](https://reviewable.io/reviews/ratpack/ratpack/1639)

### CODE REVIEW

**Comment by johnrengelman** [comment]
@jprinet is this everything you've been looking at now or do you have some additional items?

**Comment by jprinet** [comment]
> @jprinet is this everything you've been looking at now or do you have some additional items?

This is complete @johnrengelman , I've run the regular 5 experiments you've been through during GE trial to check for possible improvements on caching or build incrementality and all my findings are solved with this PR.

The overall state was good, only the `ratpack-version.txt` created under `src` folder hierarchy having some cascading effects on up-to-date checks of the next build happening after a clean build.

**Review by johnrengelman — APPROVED** [review]

**Comment by johnrengelman** [comment]
@jprinet - in case you care, there was an implicit task dependency warning being raised from this and I slightly adjusted this change here - https://github.com/ratpack/ratpack/commit/487e95ddf49d5bc5657c3a5e18756210718e0e9c so that the `writeVersionFile` task output is added to the `sourceSet`

**Comment by jprinet** [comment]
Thanks for this @johnrengelman, I just didn't notice 😅

**Pull request merged**
