### PR TITLE
Upgrade netty to 4.1.17.Final

### PR DESCRIPTION
**Pull request by LukeJoeDavis**
Removed test that tested for content-length on responses that have no content.
This out of spec test is the only one that failed on the upgrade to Netty

---
This change is [Reviewable](https://reviewable.io/reviews/ratpack/ratpack/1295)

### CODE REVIEW

**Comment by beckje01** [comment]
There are still 5 failing tests for this upgrade https://scans.gradle.com/s/qht2chux7uqzk

**Comment by ldaley** [comment]
That this fails on Linux and not Mac OS points to a regression in Netty with the epoll transport. I'm looking into it.

**Comment by ldaley** [comment]
It turns out that it's a Netty issue: https://github.com/netty/netty/issues/7443

I'm going to workaround this in the tests and put the upgrade in. It's an obscure thing that people are unlikely to hit in a real app.

**Comment by ldaley** [comment]
I've cherry picked this to 1.5.x.

**Pull request closed without merging**
