### PR TITLE
Closes #850. ReloadHandler should handle all message types.

### LINKED ISSUE #850: Request hang when running in development mode with concurrent requests
Example app: https://github.com/timyates/ratpack-logging-issue
Get output:
```
21:17:36.836 [ratpack-compute-1-6] DEBUG i.n.channel.DefaultChannelPipeline - Discarded inbound message DefaultLastHttpContent(data: SlicedByteBuf(ridx: 0, widx: 139, cap: 139/139, unwrapped: PooledUnsafeDirectByteBuf(ridx: 278, widx: 278, cap: 1024)), decoderResult: success) that reached at the tail of the pipeline. Please check your pipeline configuration.
```

Debugging has the message being printed before `channelRead` is called in `NettyHandlerAdapter`

### PR DESCRIPTION
**Pull request by johnrengelman**
[Review on Reviewable](https://reviewable.io/reviews/ratpack/ratpack/851)

### CODE REVIEW

**Comment by alkemist** [comment]
No test?

**Comment by johnrengelman** [comment]
Oh, you're so demanding....couldn't think of how to issue concurrent requests reliably off the top of my head....but I'll get one added.

**Comment by alkemist** [comment]
It doesn't have to deterministically trigger this condition, but if it's triggered sometimes by concurrent requests then having a test that fires concurrently that _never_ fails is good enough.

**Comment by johnrengelman** [comment]
Ok. I'll get something in soon so we can merge this.
I think Danny had another issue that was similar that's very important to
get in and released soon too.

**Comment by johnrengelman** [comment]
Updated w/ spec...test actually did exhibit the problem, so that's good.

**Comment by johnrengelman** [comment]
@ratpack/committers ping

**Comment by alkemist** [comment]
Just that one test fix, then pls merge.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ratpack-core/src/test/groovy/ratpack/server/RatpackServerTestSpec.groovy, line 241 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/851#-K5heA_5IefF3kdZeqnk:-K5heA_5IefF3kdZeqnl:-6094302) ([raw file](https://github.com/ratpack/ratpack/blob/4a209ceacbdf6a37b6fcd136756341d36e98a4d2/ratpack-core/src/test/groovy/ratpack/server/RatpackServerTestSpec.groovy#L241)):*
Should be GroovyEmbeddedApp instead of RatpackServer

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/851#-:-K5heO_2OO7N5xD9uiTZ:1241710467)*

**Pull request merged**
