### PR TITLE
MS Word style quotes don't render well in JavaDocs

### PR DESCRIPTION
**Pull request by aaronzirbes**
see http://ratpack.io/manual/current/api/ratpack/server/Service.html

[Review on Reviewable](https://reviewable.io/reviews/ratpack/ratpack/761)

### CODE REVIEW

**Comment by danhyun** [comment]
Thanks for this @aaronzirbes smart quotes are the devil

**Comment by danhyun** [comment]
Please add yourself to the contributors list https://github.com/ratpack/ratpack/blob/master/ratpack-manual/src/content/chapters/99-about-the-project.md

**Comment by danhyun** [comment]
It actually looks like something went wrong while creating these docs:

image

**Comment by alkemist** [comment]
We won't be removing the smart quotes. We need to fix the automation that let the docs be built in something other than Unicode.

Thanks for pull request regardless.

**Comment by danhyun** [comment]
This is addressed via this commit https://github.com/ratpack/ratpack/commit/8481348ddab5b643924060b4ad20f7980f4a2058

**Pull request closed without merging**
