### PR TITLE
Teach GroovyEmbeddedApp about ratpack.groovy syntax. Closes #925.

### LINKED ISSUE #925: GroovyEmbeddedApp should implement ratpack.groovy.Groovy.Ratpack
I don't see any reason why it couldn't do so and if it did then you could use the familiar dsl available in Ratpack Groovy scripts when defining embedded applications.

### PR DESCRIPTION
**Pull request by johnrengelman**
This change is [Reviewable](https://reviewable.io/reviews/ratpack/ratpack/992)

### CODE REVIEW

**Comment by alkemist** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[ratpack-groovy-test/src/main/java/ratpack/groovy/test/embed/GroovyEmbeddedApp.java, line 84 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/992#-KJ0ANxY1o9iv8RJKOQh:-KJ0ANxZRO1stSujXe1Q:2769688) ([raw file](https://github.com/ratpack/ratpack/blob/0738bb14b38b954dd70ac8d7bdb94dba94995999/ratpack-groovy-test/src/main/java/ratpack/groovy/test/embed/GroovyEmbeddedApp.java#L84)):*
> ```Java
>   }
> 
>   static GroovyEmbeddedApp ratpack(@DelegatesTo(value = Groovy.Ratpack.class, strategy = Closure.DELEGATE_FIRST) Closure<?> script) throws Exception {
> ```

Needs at least @since.

---

*[ratpack-groovy/src/main/java/ratpack/groovy/internal/StandaloneScriptBacking.java, line 66 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/992#-KJ0AFVbohHzOiDETyy5:-KJ0AFVbohHzOiDETyy6:-1237716647) ([raw file](https://github.com/ratpack/ratpack/blob/0738bb14b38b954dd70ac8d7bdb94dba94995999/ratpack-groovy/src/main/java/ratpack/groovy/internal/StandaloneScriptBacking.java#L66)):*
> ```Java
>   }
> 
>   public static class ConsoleScriptConfigurer implements Action<RatpackServerSpec> {
> ```

We should move this to top level and give it a better name now that it has a broader job.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/992)*

**Comment by johnrengelman** [comment]
@ratpack/commiters - if someone could take this over the line with @alkemist's comments that would be awesome. I'm going to be indisposed for the next couple of weeks. 😀

**Comment by erdi** [comment]
Will do.

**Comment by johnrengelman** [comment]
Made the tweak per @alkemist's review

<details><summary><i>Previously, erdi (Marcin Erdmann) wrote…</i></summary>
> Will do.
</details>


---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/992#-:-KJQqCheep8BEpuv6HuM:-1593351402)*

**Pull request merged**
