### PR TITLE
Model executions as a tree allowing upward traversal

### PR DESCRIPTION
**Pull request by ldaley**
The current execution when forking an execution becomes the parent of the forked execution.

---
This change is [Reviewable](https://reviewable.io/reviews/ratpack/ratpack/1311)

### CODE REVIEW

**Comment by ldaley** [comment]
@tomdcc if you get a chance, it would be very helpful if you could evaluate whether this would meet your needs for mini profiler.

**Comment by tomdcc** [comment]
@ldaley I had a play and it does indeed do basically what I need.

I wrote a long paragraph here about another change that would make life even nicer, only to see that it's already on your radar: https://github.com/ratpack/ratpack/issues/1027

The combination of the two is basically my wishlist for miniprofiler support.

**Comment by ldaley** [comment]
@johnrengelman can I get a review please.

**Comment by johnrengelman** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[ratpack-exec/src/main/java/ratpack/exec/ExecSpec.java, line 90 at r1](https://reviewable.io:443/reviews/ratpack/ratpack/1311#-L2VTNnw8GGzuLOj1r6m:-L2VTNnw8GGzuLOj1r6n:b-hpy9x8) ([raw file](https://github.com/ratpack/ratpack/blob/ca1a062ff47134ff48090fc16a270e4536da6c6f/ratpack-exec/src/main/java/ratpack/exec/ExecSpec.java#L90)):*
> ```Java
>    * <p>
>    * When forking from another execution, the current execution for the callback is <i>that</i> execution
>    * and not the execution being created. That is, it is the parent execution of the new execution.
> ```

I'm a bit unclear on what this is saying. Is it saying that the `Execution` passed to the provided `Action` is now the parent execution when being forked? or is it saying that when `Action.execute` is called, if I called `Execution.current()` within it, the value is the parent `Execution` at that moment?

---

*[ratpack-exec/src/main/java/ratpack/exec/ExecutionRef.java, line 26 at r1](https://reviewable.io:443/reviews/ratpack/ratpack/1311#-L2VTw0L2GZ6uLGri4rz:-L2VTw0L2GZ6uLGri4s-:b-g6u013) ([raw file](https://github.com/ratpack/ratpack/blob/ca1a062ff47134ff48090fc16a270e4536da6c6f/ratpack-exec/src/main/java/ratpack/exec/ExecutionRef.java#L26)):*
> ```Java
>  * A reference to an {@link Execution} that is usable from outside of it.
>  *
>  * An execution ref is-a registry.
> ```

`is-a`? on purpose or typo?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1311)*

**Comment by johnrengelman** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[ratpack-exec/src/main/java/ratpack/exec/ExecSpec.java, line 90 at r1](https://reviewable.io:443/reviews/ratpack/ratpack/1311#-L2VTNnw8GGzuLOj1r6m:-L2VY5MQskbH8l755Q4x:b-rewxez) ([raw file](https://github.com/ratpack/ratpack/blob/ca1a062ff47134ff48090fc16a270e4536da6c6f/ratpack-exec/src/main/java/ratpack/exec/ExecSpec.java#L90)):*
<details><summary><i>Previously, johnrengelman (John Engelman) wrote…</i></summary><blockquote>

I'm a bit unclear on what this is saying. Is it saying that the `Execution` passed to the provided `Action` is now the parent execution when being forked? or is it saying that when `Action.execute` is called, if I called `Execution.current()` within it, the value is the parent `Execution` at that moment?
</blockquote></details>

I understand the structure now after reading through the specs, but I think that text the here is still a bit unclear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1311)*

**Comment by ldaley** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[ratpack-exec/src/main/java/ratpack/exec/ExecSpec.java, line 90 at r1](https://reviewable.io:443/reviews/ratpack/ratpack/1311#-L2VTNnw8GGzuLOj1r6m:-L2YAfUJWCE-dasACk-Y:bf4kwot) ([raw file](https://github.com/ratpack/ratpack/blob/ca1a062ff47134ff48090fc16a270e4536da6c6f/ratpack-exec/src/main/java/ratpack/exec/ExecSpec.java#L90)):*
<details><summary><i>Previously, johnrengelman (John Engelman) wrote…</i></summary><blockquote>

I understand the structure now after reading through the specs, but I think that text the here is still a bit unclear.
</blockquote></details>

Pushed what is hopefully an improvement.

---

*[ratpack-exec/src/main/java/ratpack/exec/ExecutionRef.java, line 26 at r1](https://reviewable.io:443/reviews/ratpack/ratpack/1311#-L2VTw0L2GZ6uLGri4rz:-L2Y9CcTUWeiPgy16-mY:b-3hr9tv) ([raw file](https://github.com/ratpack/ratpack/blob/ca1a062ff47134ff48090fc16a270e4536da6c6f/ratpack-exec/src/main/java/ratpack/exec/ExecutionRef.java#L26)):*
<details><summary><i>Previously, johnrengelman (John Engelman) wrote…</i></summary><blockquote>

`is-a`? on purpose or typo?
</blockquote></details>

Intentional: https://en.wikipedia.org/wiki/Is-a

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1311)*

**Comment by johnrengelman** [comment]
Reviewed 12 of 13 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1311)*

**Comment by johnrengelman** [comment]
Looks great to me!

**Pull request merged**
