### PR TITLE
First pass at relative paths for json/yaml based config files #725

### PR DESCRIPTION
**Pull request by danhyun**
[Review on Reviewable](https://reviewable.io/reviews/ratpack/ratpack/737)

### CODE REVIEW

**Comment by danhyun** [comment]
Reviewed 16 of 16 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/737)

**Comment by alkemist** [comment]
Review status: 0 of 16 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[ratpack-core/src/main/java/ratpack/config/ConfigDataBuilder.java, line 350 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/737#-JwG_Uh8oAEru3g_SgGk)** ([raw file](https://github.com/ratpack/ratpack/blob/9f007196254a149e8ff70456cf448737f621d91e/ratpack-core/src/main/java/ratpack/config/ConfigDataBuilder.java#L350)):</sup>
I don't think this belongs here. ConfigData doesn't really have any use for this, and it's mixing concerns. 

This leaves the question of how to resolve relative paths when ConfigDataBuilder is used by itself. Options:

1. Relative to working directory
2. Relative to file system root (i.e. implicitly absolute)

Will also need docs when moved to ServerConfigBuilder.

---

<sup>**[ratpack-core/src/main/java/ratpack/config/ConfigSource.java, line 34 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/737#-JwGZm5Ekjnc4NQ4h5mJ)** ([raw file](https://github.com/ratpack/ratpack/blob/9f007196254a149e8ff70456cf448737f621d91e/ratpack-core/src/main/java/ratpack/config/ConfigSource.java#L34)):</sup>
This is too wide a type to pass in. It should just take ObjectMapper.

---

<sup>**[ratpack-core/src/main/java/ratpack/config/internal/source/JacksonConfigSource.java, line 58 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/737#-JwJTVZOqgTxNEJpxNzK)** ([raw file](https://github.com/ratpack/ratpack/blob/9f007196254a149e8ff70456cf448737f621d91e/ratpack-core/src/main/java/ratpack/config/internal/source/JacksonConfigSource.java#L58)):</sup>
We need to find another solution than requiring all config sources to duplicate this logic.

---

<sup>**[ratpack-core/src/test/groovy/ratpack/config/YamlConfigSpec.groovy, line 99 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/737#-JwG_HWSIWxSAsZl8CVU)** ([raw file](https://github.com/ratpack/ratpack/blob/9f007196254a149e8ff70456cf448737f621d91e/ratpack-core/src/test/groovy/ratpack/config/YamlConfigSpec.groovy#L99)):</sup>
This should error (fail fast) and tell the user that baseDir can't be set, not just ignore it.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/737)

**Comment by danhyun** [comment]
<sup>**[ratpack-core/src/main/java/ratpack/config/ConfigDataBuilder.java, line 350 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/737#-JwG_Uh8oAEru3g_SgGk)** ([raw file](https://github.com/ratpack/ratpack/blob/9f007196254a149e8ff70456cf448737f621d91e/ratpack-core/src/main/java/ratpack/config/ConfigDataBuilder.java#L350)):</sup>
How do we know what the working dir is? Via `BaseDirFinder`?
Relative to FS root is a bit tricky on Windows but could work everywhere else.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/737)

**Comment by danhyun** [comment]
<sup>**[ratpack-core/src/main/java/ratpack/config/internal/source/JacksonConfigSource.java, line 58 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/737#-JwJTVZOqgTxNEJpxNzK)** ([raw file](https://github.com/ratpack/ratpack/blob/9f007196254a149e8ff70456cf448737f621d91e/ratpack-core/src/main/java/ratpack/config/internal/source/JacksonConfigSource.java#L58)):</sup>
So in this situation I was thinking properties and env sources _could_ set `baseDir`, but then `baseDir`would become a moving target while resolving the relative paths.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/737)

**Comment by danhyun** [comment]
<sup>**[ratpack-core/src/test/groovy/ratpack/config/YamlConfigSpec.groovy, line 99 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/737#-JwG_HWSIWxSAsZl8CVU)** ([raw file](https://github.com/ratpack/ratpack/blob/9f007196254a149e8ff70456cf448737f621d91e/ratpack-core/src/test/groovy/ratpack/config/YamlConfigSpec.groovy#L99)):</sup>
That's a good point.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/737)

**Comment by danhyun** [comment]
<sup>**[ratpack-core/src/main/java/ratpack/config/ConfigSource.java, line 34 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/737#-JwGZm5Ekjnc4NQ4h5mJ)** ([raw file](https://github.com/ratpack/ratpack/blob/9f007196254a149e8ff70456cf448737f621d91e/ratpack-core/src/main/java/ratpack/config/ConfigSource.java#L34)):</sup>
I agree.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/737)

**Comment by alkemist** [comment]
@danhyun can you please close this and reopen a PR based on relative-config branch, that we any of us can work on it.

**Comment by danhyun** [comment]
Opened 755

**Pull request closed without merging**
