### PR TITLE
Simplify parsers, and remove the jackson-guice lib (inlined into core).

### PR DESCRIPTION
**Pull request by alkemist**
[Review on Reviewable](https://reviewable.io/reviews/ratpack/ratpack/740)

### CODE REVIEW

**Comment by beckje01** [comment]
The parsers are starting to get more understandable. 

We also wanted to start updating the changelog file with PRs as well correct?

---

Review status: 0 of 38 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[ratpack-manual/src/content/chapters/30-guice.md, line 31 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/740#-Jvxrdyl1D4UlFcEZ9Pt)** ([raw file](https://github.com/ratpack/ratpack/blob/d42aee9aeb57817f42bc57113145cdbc3daf2969/ratpack-manual/src/content/chapters/30-guice.md#L31)):</sup>
Do we not want this section any more or just that we don't have any good example for it now?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/740)

**Comment by beckje01** [comment]
Reviewed 38 of 38 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/740)

**Comment by alkemist** [comment]
Added to the release notes.

---

Review status: 36 of 39 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[ratpack-manual/src/content/chapters/30-guice.md, line 31 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/740#-Jvxrdyl1D4UlFcEZ9Pt)** ([raw file](https://github.com/ratpack/ratpack/blob/d42aee9aeb57817f42bc57113145cdbc3daf2969/ratpack-manual/src/content/chapters/30-guice.md#L31)):</sup>
We should have something for this. Let's deal with that in a separate change.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/740)

**Comment by beckje01** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[ratpack-manual/src/content/chapters/33-jackson.md, line 171 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/740#-Jw2pYtBi_o1b9RXeybq)** ([raw file](https://github.com/ratpack/ratpack/blob/07973238880487c027fee562d69612deb3b183a7/ratpack-manual/src/content/chapters/33-jackson.md#L171)):</sup>
This is nice and easy to deal with.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/740)

**Pull request merged**
