### PR TITLE
Adding pre-emptive null check on Content-Type

### PR DESCRIPTION
**Pull request by collisonchris**
This change is [Reviewable](https://reviewable.io/reviews/ratpack/ratpack/1334)

### CODE REVIEW

**Comment by collisonchris** [comment]
Think this is what you're after in #1316; let me know if any additional updates/tests would be needed

**Comment by collisonchris** [comment]
Looks like I hit a couple of time bombs:

`ratpack.site.LinkCrawlSpec > site has no bad links FAILED
    Condition not satisfied:

    errored.empty
    |       |
    |       false
    https://github.com/Netflix/Hystrix/wiki/Dashboard (referrers: [http://localhost:41459/manual/1.6.0/api/ratpack/hystrix/HystrixMetricsEventStreamHandler.html, http://localhost:41459/manual/1.6.0/hystrix.html, http://localhost:41459/manual/1.6.0/api/ratpack/hystrix/HystrixModule.html], errors: [HTTP status: 404], attempts: 3)
        at ratpack.site.LinkCrawlSpec.site has no bad links(LinkCrawlSpec.groovy:92)`

^this failure is caused by broken links on https://github.com/Netflix; it can be fixed by adding 'https://github.com/Netflix/Hystrix' to the allowBroken list.

`ratpack.util.internal.TypeCoercingPropertiesSpec > asInetAddress throws an exception if the property value cannot be resolved as a host FAILED
    Expected exception of type 'java.net.UnknownHostException', but no exception was thrown
        at org.spockframework.lang.SpecInternals.checkExceptionThrown(SpecInternals.java:79)
        at org.spockframework.lang.SpecInternals.thrownImpl(SpecInternals.java:66)
        at ratpack.util.internal.TypeCoercingPropertiesSpec.asInetAddress throws an exception if the property value cannot be resolved as a host(TypeCoercingPropertiesSpec.groovy:130)`

^this failure is due to 'null.ratpackframework.org' now returning a valid DNS response; dig null.ratpackframework.org returns a valid IP; this can be fixed by changing the bad hostname to something that still returns no entry

Added a commit to address these two

**Comment by rhart** [comment]
I don't think we should add the link to the allowBroken list.  It's not broken, it has permanently been moved.  The link should be changed to `https://github.com/Netflix-Skunkworks/hystrix-dashboard/wiki` and possibly the documentation updated if required.  But that does not have to happen as part of this PR.

**Comment by collisonchris** [comment]
@rhart Makes sense, I'm ok doing the links & doc update and removing the Hystrix from the allowBroken list.

**Comment by rhart** [comment]
Awesome, thanks!

**Comment by beckje01** [comment]
Merged in #1338

**Pull request closed without merging**
