### PR TITLE
Execute promises in parallel and return promise for all results

### PR DESCRIPTION
**Pull request by drmaas**
This change is [Reviewable](https://reviewable.io/reviews/ratpack/ratpack/964)

### CODE REVIEW

**Comment by drmaas** [comment]
Some background on this:

We frequently have use cases where we have to issue multiple concurrent IO requests, say to Cassandra. We want to not only issue the requests as non-blocking and/or in parallel on separate IO threads, but process the responses in parallel as well on ratpack execution threads.

After significant amounts of performance testing, this code scales and performs better than any alternatives, like using RxJava.

**Comment by alkemist** [comment]
Hi @drmaas ,

This is great stuff and we are very grateful for the contribution. I'm a little swamped right now, but will do my best to get to this very soon.

**Comment by drmaas** [comment]
Is there a scenario where we want to do the same thing, but without forking new executions for each promise? I'm thinking that would be useful if someone wanted to ensure execution order. Let me know your thoughts.

**Comment by alkemist** [comment]
@drmaas I'm going to close this in favour of #977. It will support the same use case, but provides a space to grow the options for this kind of thing. Please check it out and provide any feedback.

**Pull request closed without merging**
