### PR TITLE
Adds information how to enable live changes in quickstart manual

### PR DESCRIPTION
**Pull request by mlevvy**
[Review on Reviewable](https://reviewable.io/reviews/ratpack/ratpack/837)

### CODE REVIEW

**Comment by alkemist** [comment]
Hi @mlevvy 

Thanks for your contribution. Could you elaborate here on when/why you need to explicitly enable development mode? It's supposed to be implicitly enabled when running via the `groovy` command.

**Comment by mlevvy** [comment]
In the tutorial I’ve found following sentences: “Changes to the `ratpack.groovy` file are live during development.”. Unfortunately, when I’ve tried to do this, it seems not to work (both for Grab and Gradle plugin option). 

People on slack, told me, that live changes options works when:
- when using Grab, with development mode. 
- when using grade plugin, with —continuous option, to live edit.

I’ve tested it, confirmed it, and do this pull request with updated manual.

**Comment by alkemist** [comment]
Can you please provide some instructions I can follow to run the app and not have it respect changes.

**Comment by mlevvy** [comment]
If you try to run this [program with groovy script](http://ratpack.io/manual/current/quick-start.html#using_a_groovy_script). 
* Run this file
* Edit and save changes
* Perform request
* Your changes to the file are not included.

My pull request clearly explains how to enable this functionality.

**Comment by alkemist** [comment]
@mlevvy thanks for the PR and report. I've fixed this so that it works as advertised in the docs as they were.

https://github.com/ratpack/ratpack/commit/04847e0c92d397a648a26a4be6f7af7ced85e13e

Thanks.

**Pull request closed without merging**
