### PR TITLE
allow configurable idle timeout for http client

### PR DESCRIPTION
**Pull request by drmaas**
This change is [Reviewable](https://reviewable.io/reviews/ratpack/ratpack/1406)

### CODE REVIEW

**Comment by drmaas** [comment]
This is related to #1043,  but instead of auto-reconnecting, connections will be closed off if idle for greater than the configured period.

**Comment by johnrengelman** [comment]
@drmaas can you rebase this build to master?

**Comment by drmaas** [comment]
@johnrengelman is there any blocker preventing this from being merged?

**Comment by beckje01** [comment]
@drmaas I see two test failures in CI

**Comment by drmaas** [comment]
@beckje01 I'm out of ideas - the tests compile and pass locally.

**Comment by beckje01** [comment]
@drmaas try a rebase and see if they are ok on CI after that

**Comment by beckje01** [comment]
If that doesn't work I'll try

**Comment by drmaas** [comment]
@beckje01 🤔

**Comment by drmaas** [comment]
Now that thonking time is over it should compile and pass tests.

**Comment by drmaas** [comment]
@beckje01 should be all set now

**Comment by beckje01** [comment]
Great I should be on this later tonight

**Pull request merged**
