### PR TITLE
provide a default connect timeout for http client, closes #1230

### LINKED ISSUE #1230: Provide configurable default connect timeout for http client
Currently only read timeout is configurable on http client. It will be useful to configure the connect timeout to values other than 30 seconds. For example when using retrofit, we are not able to specify timeouts per request.

### PR DESCRIPTION
**Pull request by drmaas**
This change is [Reviewable](https://reviewable.io/reviews/ratpack/ratpack/1231)

### CODE REVIEW

**Comment by drmaas** [comment]
Error appears to be in `ClientSideSessionSpec.can use algorithm DES/CBC/NoPadding`

**Comment by beckje01** [comment]
Can you retrigger CI? Master should be passing now.

**Comment by drmaas** [comment]
@beckje01 looks like the CI link went away :(

**Comment by drmaas** [comment]
Opened #1239 in an attempt to retrigger build

**Pull request closed without merging**
