### PR TITLE
Update page title checked for in SiteSmokeSpec

### PR DESCRIPTION
**Pull request by stianl**
Correct page title is checked for a few places

[Review on Reviewable](https://reviewable.io/reviews/ratpack/ratpack/812)

### CODE REVIEW

**Comment by danhyun** [comment]
Thanks for the PR Stian,

This is what I'm seeing for the title of the index page

image


Where are you seeing the title change?

**Comment by stianl** [comment]
https://github.com/ratpack/ratpack/blob/bbf15e82d4082e569fa7817db47157805975c20e/ratpack-site/src/ratpack/templates/layout.gtpl


On Mon, 12 Oct 2015 16:27 Danny <notifications@github.com> wrote:

Thanks for the PR Stian,

This is what I'm seeing for the title of the index page

<
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
img
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
src
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
="
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
https
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
://
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
ci3.googleusercontent.com
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
/
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
proxy
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
/4MaFCGLlJY8LvaZsloPIWOhCN7_
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
skK
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
_
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
x2ovoHoRVrVs5BhfWVFekfahbN0YpMxE3E0EaIWgfckHxqAP73NHui5g0FrMcjONExaycqFjhi2gNBIENUDVau7hYfRUXGySak-sUo6FfL3b8m2jKrTs0xlMx
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
_
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
SnC8ncOR8M
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
=s0-d-e1-ft#https://
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
cloud.githubusercontent.com
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
/
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
assets
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
/1033018/10430175/
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
b9954d54-70cb-11e5-971d-0542519ded41.png
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>
">
<https://cloud.githubusercontent.com/assets/1033018/10430175/b9954d54-70cb-11e5-971d-0542519ded41.png>

Where are you seeing the title change?

—
Reply to this email directly or view
<https://github.com/ratpack/ratpack/pull/812#issuecomment-147413003> it
<https://github.com/ratpack/ratpack/pull/812#issuecomment-147413003>on
<https://github.com/ratpack/ratpack/pull/812#issuecomment-147413003>
<https://github.com/ratpack/ratpack/pull/812#issuecomment-147413003>GitHub
<https://github.com/ratpack/ratpack/pull/812#issuecomment-147413003>.

**Comment by danhyun** [comment]
That's a good point, I'll look a bit into where the current title is coming from

**Comment by danhyun** [comment]
Thanks for this, do you mind adding yourself to the contributors section https://github.com/ratpack/ratpack/blob/master/ratpack-manual/src/content/chapters/99-about-the-project.md ?

**Comment by danhyun** [comment]
NOTE: Broke with this change https://github.com/ratpack/ratpack/commit/bbf15e82d4082e569fa7817db47157805975c20e#diff-d096f92a0cc34ad86139e28fcd920b9f

**Comment by alkemist** [comment]
Thanks @stianl

**Pull request merged**
