### PR TITLE
ability to specify a predicate for retries

### PR DESCRIPTION
**Pull request by drmaas**
Use Case

This will allow users to retry only upon certain exceptions and conditions. For example, to retry only on connection timeout/reset errors, the predicate could match `IOException`.

TODO

~~* Add tests for predicate~~

---
This change is [Reviewable](https://reviewable.io/reviews/ratpack/ratpack/1466)

### CODE REVIEW

**Comment by johnrengelman** [comment]
The `onError` function passed to `retry(RetryPolicy, Function)` (https://github.com/ratpack/ratpack/blob/master/ratpack-exec/src/main/java/ratpack/exec/Promise.java#L2445) allows for some level of control here. `onError` receives the attempt number and the underlying exception. Any exception thrown from `onError` bypasses the retry policy and is sent downstream.

**Comment by drmaas** [comment]
Hm, that would also work, but seems a bit awkward and non-obvious.

**Comment by drmaas** [comment]
@johnrengelman another option might be to overload retry - 

1) `retry(RetryPolicy retryPolicy, Predicate<? super Throwable> matcher)`
or 
2) `retryIf(Predicate<? super Throwable> matcher, RetryPolicy retryPolicy, BiAction<? super Integer, ? super Throwable> onError)`

**Comment by johnrengelman** [comment]
I think I see the `retryIf(Predicate, ....)` pattern being the most appropriate implementation here and it should be fairly trivial to implement based on the semantics of `onError` that I mentioned above.

**Comment by drmaas** [comment]
Updated to add a new method `retryIf`

**Pull request merged**
