### PR TITLE
Upgrade Netty to 4.1.1.Final

### PR DESCRIPTION
**Pull request by danhyun**
Update includeSpec to be platform agnostic (Windows)

---
This change is [Reviewable](https://reviewable.io/reviews/ratpack/ratpack/1003)

### CODE REVIEW

**Comment by danhyun** [comment]
Upgrade for bug fixes and security fixes http://netty.io/news/2016/06/07/4-1-1-Final.html

**Comment by johnrengelman** [comment]
@danhyun can you break this into 2 commits, 1 for the netty upgrade, 1 for the windows patches?

**Comment by johnrengelman** [comment]
@danhyun  ping

**Comment by danhyun** [comment]
pong will address tonight

On Fri, Jun 17, 2016 at 10:12 AM, John Engelman <notifications@github.com>
wrote:

> @danhyun <https://github.com/danhyun> ping
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ratpack/ratpack/pull/1003#issuecomment-226779401>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA_DOtJ7TquSNqXsl3030z4IfzDFjAEHks5qMqtCgaJpZM4Iw5yg>
> .
>



-- 
Thanks,

Daniel Hyun
blog: http://hyunlabs.com/

**Comment by danhyun** [comment]
Added Windows fix as a separate commit

**Comment by johnrengelman** [comment]
:-/

**Comment by johnrengelman** [comment]
Merged in https://github.com/ratpack/ratpack/commit/4640160af7f8070649166c7e879bcfb6874a6fae

**Pull request closed without merging**
