### PR TITLE
Make websocket.send() return ChannelFuture.

### PR DESCRIPTION
**Pull request by achmadns**
I need a way to notify when the text is flushed into websocket client. Could you please incorporate this?

[Review on Reviewable](https://reviewable.io/reviews/ratpack/ratpack/834)

### CODE REVIEW

**Comment by alkemist** [comment]
We can't make this change. It has two problems:

1. It breaks public API
2. It exposes ChannelFuture, which is too level

Two options going forward:

1. Expose new methods to WebSocket that somehow signal that the content has been written
2. Introduce a different interface/usage pattern, perhaps based on Publisher

**Comment by achmadns** [comment]
Sorry, my English is rather...

Is there workaround for now so that I can do something when the text is written to ws client?

**Comment by alkemist** [comment]
The only thing would be to copy/clone the websocket stuff that is there and patch it to your liking. You don't necessarily need to fork Ratpack to do this.

**Comment by achmadns** [comment]
Thanks, I'll try it first.

**Pull request closed without merging**
