### PR TITLE
Provide easy access to the application registry via a server reference

### PR DESCRIPTION
**Pull request by rpalcolea**
This change is [Reviewable](https://reviewable.io/reviews/ratpack/ratpack/1301)

### CODE REVIEW

**Comment by rpalcolea** [comment]
related to https://github.com/ratpack/ratpack/issues/1282

**Comment by ldaley** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ratpack-core/src/main/java/ratpack/server/RatpackServer.java, line 199 at r1](https://reviewable.io:443/reviews/ratpack/ratpack/1301#-L01lJyk36qS9h4I1vOZ:-L01lJyk36qS9h4I1vO_:b-8k2jb7) ([raw file](https://github.com/ratpack/ratpack/blob/824cdbff11021fafdc5386ce308c7ca4b5360319/ratpack-core/src/main/java/ratpack/server/RatpackServer.java#L199)):*
> ```Java
>    * @return a Ratpack registry
>    */
>   Registry getRegistry();
> ```

Should be Optional<Registry>, and javadoc needs `@since 1.6`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1301)*

**Comment by ldaley** [comment]
@rpalcolea thank you very much!

Please see the comment feedback for some requested minor changes.

**Comment by rpalcolea** [comment]
done @ldaley 

Hope that's what you had in mind. Thanks for the feedback.

I was looking at issues for the 1.6 (https://github.com/ratpack/ratpack/milestone/50) and some issues are from 2016, are those still planned for 1.6? Wonder if there are priorities, would like to contribute if possible.

**Pull request merged**
