### PR TITLE
Add Prometheus output support to metrics library.

### PR DESCRIPTION
**Pull request by johnrengelman**
This change is [Reviewable](https://reviewable.io/reviews/ratpack/ratpack/1271)

### CODE REVIEW

**Comment by johnrengelman** [comment]
There is a problem with this in that prometheus doesn't allow metrics to start with a numeric and the ratpack metrics have some that start that way.

**Comment by ldaley** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ratpack-dropwizard-metrics/src/main/java/ratpack/dropwizard/metrics/MetricsPrometheusHandler.java, line 47 at r1](https://reviewable.io:443/reviews/ratpack/ratpack/1271#-L2SOM2ob2Dq8tQl8f0W:-L2SOM2ob2Dq8tQl8f0X:b-mih7gy) ([raw file](https://github.com/ratpack/ratpack/blob/f4c999470b5b9a9c7d12509f3c9212da5c52dc38/ratpack-dropwizard-metrics/src/main/java/ratpack/dropwizard/metrics/MetricsPrometheusHandler.java#L47)):*
> ```Java
>     ctx.getResponse().status(200);
>     StringWriter sw = new StringWriter();
>     TextFormat.write004(sw, ctx.get(CollectorRegistry.class).metricFamilySamples());
> ```

Would be worth generating this off heap.

To do this you'd need to create a ByteBuf, and create a writer that uses ByteBufOutputStream to write it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1271)*

**Comment by johnrengelman** [comment]
Updated to use a `ByteBuf` and to check for the correct name sanitize for metrics that start with digit. This was fixed here: https://github.com/prometheus/client_java/pull/314, so this will need until that change is released.

**Comment by ldaley** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ratpack-dropwizard-metrics/src/main/java/ratpack/dropwizard/metrics/MetricsPrometheusHandler.java, line 47 at r1](https://reviewable.io:443/reviews/ratpack/ratpack/1271#-L2SOM2ob2Dq8tQl8f0W:-L2YRMG1vg4dhhAwG5BP:be3rdqp) ([raw file](https://github.com/ratpack/ratpack/blob/f4c999470b5b9a9c7d12509f3c9212da5c52dc38/ratpack-dropwizard-metrics/src/main/java/ratpack/dropwizard/metrics/MetricsPrometheusHandler.java#L47)):*
<details><summary><i>Previously, ldaley (Luke Daley) wrote…</i></summary><blockquote>

Would be worth generating this off heap.

To do this you'd need to create a ByteBuf, and create a writer that uses ByteBufOutputStream to write it.
</blockquote></details>

The writer should be used in a try-with-resources block, and we need to release the bytebuf if TextFormat.write fails.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1271)*

**Comment by johnrengelman** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ratpack-dropwizard-metrics/src/main/java/ratpack/dropwizard/metrics/MetricsPrometheusHandler.java, line 47 at r1](https://reviewable.io:443/reviews/ratpack/ratpack/1271#-L2SOM2ob2Dq8tQl8f0W:-L2x6fE1iTY8ViQj9HGR:b-msrkap) ([raw file](https://github.com/ratpack/ratpack/blob/f4c999470b5b9a9c7d12509f3c9212da5c52dc38/ratpack-dropwizard-metrics/src/main/java/ratpack/dropwizard/metrics/MetricsPrometheusHandler.java#L47)):*
<details><summary><i>Previously, ldaley (Luke Daley) wrote…</i></summary><blockquote>

The writer should be used in a try-with-resources block, and we need to release the bytebuf if TextFormat.write fails.
</blockquote></details>

Should I rethrow the exception from a failed write? 
Should I set the status for the response to 500 and send it if the write fails?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1271)*

**Comment by ldaley** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ratpack-dropwizard-metrics/src/main/java/ratpack/dropwizard/metrics/MetricsPrometheusHandler.java, line 47 at r1](https://reviewable.io:443/reviews/ratpack/ratpack/1271#-L2SOM2ob2Dq8tQl8f0W:-L2xqmtexdG0Zx6LNAk-:b-ez78lu) ([raw file](https://github.com/ratpack/ratpack/blob/f4c999470b5b9a9c7d12509f3c9212da5c52dc38/ratpack-dropwizard-metrics/src/main/java/ratpack/dropwizard/metrics/MetricsPrometheusHandler.java#L47)):*
<details><summary><i>Previously, johnrengelman (John Engelman) wrote…</i></summary><blockquote>

Should I rethrow the exception from a failed write? 
Should I set the status for the response to 500 and send it if the write fails?
</blockquote></details>

- You don't need `w.flush()` (close implicitly flushes)
- You can write `ctx.getResponse().status(200).send(buf)`
- `.send(buf)` should be _outside_ the try
- The catch block should just do `buf.release();` and `throw e;` (i.e. let the error handler deal with it)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1271)*

**Comment by johnrengelman** [comment]
Updated with changes from comments.

**Comment by ldaley** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r1, 2 of 4 files at r2, 2 of 3 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1271#-:-L360shOwtH30F6Noc2s:bnfp4nl)*

**Comment by ldaley** [comment]
@johnrengelman just CI failures to go: https://scans.gradle.com/s/igdhoazczkinq/custom-values#L1

**Comment by johnrengelman** [comment]
Yup, just waiting on an upstream change to apply the fix.

**Pull request merged**
