### PR TITLE
Workaround to support Thymeleaf link URL expressions (#517)

### PR DESCRIPTION
**Pull request by todd1251**

### CODE REVIEW

**Comment by todd1251** [comment]
@Vadi: While it might be possible to exclude `servlet-api` when depending on Thymeleaf, it is a defined as a `provided` dependency in Thymeleaf's [pom.xml](https://github.com/thymeleaf/thymeleaf/blob/3.0-dev/pom.xml#L280) and used by the web context and link expression related classes. If `WebContext` is not used, then the exception noted in issue #517 is thrown. To exclude `servlet-api` completely, it would not be possible to use the link expressions (`@{...}`), unless a change is made upstream in Thymeleaf (ideally it would be *HTTP-engine-agnostic*). If someone really wanted to avoid shipping the `servlet-api` JAR then I suppose they still could, even with this change, by excluding the transitive dependency via Gradle and not using link expressions?

@alkemist: As I mentioned in the discussion of issue #517, this is probably still wrong/broken but it doesn't crash, at least. As *context path* is a servlet API concept, it being defined as an empty string here means it will never affect the resolved URL (it would otherwise be prepended). Not sure if some resolution is *supposed* to happen for relative URLs but it leaving them as-is seems like sensible behaviour to me, i.e. the browser will resolve the relative links. 

I added the test case based on the different types noted in the Thymeleaf docs on [Link URLs](http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#link-urls) and was surprised to find that it's almost a no-op ;-).

**Comment by alkemist** [comment]
Re servlet-api: Depending on the servlet-api jar is fine. Eventually, we'll have a `ratpack-servlet-adapter` thing that will depend on this and that thymeleaf depends on.

Re the links: so what exactly does this change practically give users?

**Comment by todd1251** [comment]
@alkemist: The practical benefit is that the standard Thymeleaf syntax for writing links (`@{...}`) doesn't crash. It also doesn't do anything in most cases because the context path is always empty (given that is a servlet container thing).

It's okay if you don't want to accept the change and give it more thought first. I think, ideally, Thymeleaf wouldn't depend on the servlet API directly. It is possible to just leave out the `@{...}` and links will work fine but that is counter to the Thymeleaf documentation.

**Comment by alkemist** [comment]
@todd1251 happy to merge this. Will do so later today.

Thanks.

**Comment by johnrengelman** [comment]
Failure of this PR appeared to be a caching problem on Snap. I busted the cache and re-ran and it completed successfully.

**Pull request merged**
