### PR TITLE
Support connection pooling by the HTTP client (#465).

### PR DESCRIPTION
**Pull request by alkemist**
This change is [Reviewable](https://reviewable.io/reviews/ratpack/ratpack/1020)

### CODE REVIEW

**Comment by alkemist** [comment]
@drmaas would you be able to do some manual testing of this branch as you did previously with your impl as another verification? It would be greatly appreciated.

FWIW, most of the difficult logic of what you implemented hasn't changed. I've just restructured the external API and usage patterns.

**Comment by drmaas** [comment]
Looks good. 

Pool size of 0 perf test results:

screen shot 2016-07-15 at 11 36 02 am

Pool size of 32 perf test results:

screen shot 2016-07-15 at 11 37 38 am

**Comment by tednaleid** [comment]
Review status: 0 of 43 files reviewed at latest revision, 2 unresolved discussions.

---

*[ratpack-core/src/main/java/ratpack/service/Service.java, line 243 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/1020#-KMjtU8z8O_-hPijw7L8:-KMjtU8z8O_-hPijw7L9:1005456642) ([raw file](https://github.com/ratpack/ratpack/blob/1950c5c41d1232f9121fc96f8b510e34101c786e/ratpack-core/src/main/java/ratpack/service/Service.java#L243)):*
> ```Java
>    * Creates a service that executes the given action as the {@link #onStart(StartEvent)} implementation.
>    * <p>
>    * This can be used to of a service implementation from a lambda expression,
> ```

I think the changes to this file were unintentional and should be reverted.

---

*[ratpack-retrofit2/src/main/java/ratpack/retrofit/RatpackRetrofit.java, line 133 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/1020#-KMjyjk-nZyCKpmJ-XNt:-KMjyjk0Ei4PDoZIU21E:856762465) ([raw file](https://github.com/ratpack/ratpack/blob/1950c5c41d1232f9121fc96f8b510e34101c786e/ratpack-retrofit2/src/main/java/ratpack/retrofit/RatpackRetrofit.java#L133)):*
> ```Java
>      * <p>
>      * The resulting Retrofit instance can be re-used to generate multiple client interfaces which share the same base URI.
>      * @return the Retrofit instance to of client interfaces
> ```

bad find/replace?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1020)*

**Comment by alkemist** [comment]
Review status: 0 of 43 files reviewed at latest revision, 2 unresolved discussions.

---

*[ratpack-core/src/main/java/ratpack/service/Service.java, line 243 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/1020#-KMjtU8z8O_-hPijw7L8:-KMlVv_Suno2n7OLeHOh:160383661) ([raw file](https://github.com/ratpack/ratpack/blob/1950c5c41d1232f9121fc96f8b510e34101c786e/ratpack-core/src/main/java/ratpack/service/Service.java#L243)):*
<details><summary><i>Previously, tednaleid (Ted Naleid) wrote…</i></summary>
> I think the changes to this file were unintentional and should be reverted.
</details>
OK.

---

*[ratpack-retrofit2/src/main/java/ratpack/retrofit/RatpackRetrofit.java, line 133 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/1020#-KMjyjk-nZyCKpmJ-XNt:-KMlVnVYw_SsEoCxOy_r:160383661) ([raw file](https://github.com/ratpack/ratpack/blob/1950c5c41d1232f9121fc96f8b510e34101c786e/ratpack-retrofit2/src/main/java/ratpack/retrofit/RatpackRetrofit.java#L133)):*
<details><summary><i>Previously, tednaleid (Ted Naleid) wrote…</i></summary>
> bad find/replace?
</details>
OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ratpack/ratpack/1020)*

**Pull request closed without merging**
