### PR TITLE
Some documentation for WebSockets class

### PR DESCRIPTION
**Pull request by gillius**
I'm brand new to Ratpack and I was exploring it to see if I could make a microservice with websockets. I found the documentation very lacking and it took me a very long time to figure out, so I thought I'd contribute what I found out to the Javadoc.

I manually tested the Java code in the JavaDoc, but I think it's supposed to be automatically tested somehow. I tried my best to get gradlew openManual to run but it would not run compass due to #607.

There are two methods I didn't document. I still haven't figured out what they do or how to use them, but I figure they must have to do with receiving data from the clients.

### CODE REVIEW

**Comment by gillius** [comment]
I figured out you have to run as bash and as admin under Windows at least once, then you can compile compass. That let me get to the javadoc execution, which fails in the same way Travis CI does, so I will clean this up.

**Comment by gillius** [comment]
Fixed my issues, it builds locally now how I wanted it with openManual task and I've rebased and squashed the commits.

**Comment by gillius** [comment]
Travis CI says failed although I can't find any errors in there related to my documentation.

**Comment by danhyun** [comment]
@gillius firstly thanks so much for the contribution! We've been having issues with Travis killing our builds while in progress. What I can do is set up a personal build pointing to your branch on snap-ci and use that as the basis for the PR.

**Comment by gillius** [comment]
Well, that's up to you... I mean it is just a JavaDoc update. I got the impression that somehow the Javadoc is actually compiled and checked somehow. So far I've only been running open/packageManual. If you want me to run and check a certain build just to make sure it's 100% OK then I'm willing to do it.

**Comment by danhyun** [comment]
You are correct, the project is set up to pull out code from javadoc to
ensure that the code is valid. Ideally we'd run `./gradlew clean check` to
ensure that everything checks out.

On Sun, Mar 15, 2015 at 11:00 PM, Jason Winnebeck <notifications@github.com>
wrote:

> Well, that's up to you... I mean it is just a JavaDoc update. I got the
> impression that somehow the Javadoc is actually compiled and checked
> somehow. So far I've only been running open/packageManual. If you want me
> to run and check a certain build just to make sure it's 100% OK then I'm
> willing to do it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ratpack/ratpack/pull/608#issuecomment-81365098>.
>



-- 
Thanks,

Daniel Hyun
blog: http://hyunlabs.com/

**Comment by danhyun** [comment]
I've started a pipeline for your `wsdoc` branch here https://snap-ci.com/danhyun/ratpack/branch/wsdoc

**Comment by erdi** [comment]
If we are having issues with Travis but not with Snap why don't we enable PR building on Snap instead? Geb is using it and it works pretty well. I know that @alkemist did not like the idea some time ago but I don't remember what the reason was. Maybe it's time to revisit.

**Comment by danhyun** [comment]
Perhaps it's time to revisit as Travis keeps dying on us and Snap seems to be running just fine.

**Comment by danhyun** [comment]
It seems that your build is failing, here's the stacktrace from Snapci:

```
ratpack.manual.snippets.executer.CompileException: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
ratpack.websocket.WebSockets: 20: expecting ')', found '->' @ line 20, column 32.
    chain.get("whatever", context -> {
                                  ^

1 error

	at ratpack.websocket.WebSockets.javadoc(WebSockets.java:50)
	at ratpack.manual.snippets.executer.GroovySnippetExecuter.execute(GroovySnippetExecuter.java:76)
	at ratpack.manual.snippets.junit.SnippetRunner.run(SnippetRunner.java:46)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
ratpack.websocket.WebSockets: 20: expecting ')', found '->' @ line 20, column 32.
    chain.get("whatever", context -> {
                                  ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:309)
	at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:149)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:119)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:131)
	at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:359)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:142)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.parseCST(AntlrParserPlugin.java:108)
	at org.codehaus.groovy.control.SourceUnit.parse(SourceUnit.java:236)
	at org.codehaus.groovy.control.CompilationUnit$1.call(CompilationUnit.java:164)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:928)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:590)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:566)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:543)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:297)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:267)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:692)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:704)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:740)
	at ratpack.manual.snippets.executer.GroovySnippetExecuter.execute(GroovySnippetExecuter.java:71)
	... 9 more
```

**Comment by danhyun** [comment]
Build 3 has the artifacts available for download https://snap-ci.com/danhyun/ratpack/branch/wsdoc

**Comment by gillius** [comment]
It looks like it's trying to parse the Java code as Groovy, why? It's in a Java class and I followed the example from MetricsWebsocketBroadcastHandler, which also uses "java-chain-dsl" (and not groovy-chain-dsl). I also picked Java instead of Groovy (interestingly enough this is my first Java 8 code because I've been in Groovy for so long), because https://github.com/ratpack/ratpack/blob/master/CONTRIBUTING.md#coding-style-guidelines said so. If the desire for examples are to be Groovy I'd happily re-write that as a Groovy.

I l ook at JavaChainDslFixure and it extends GroovyScriptFixture. I guess I don't get it, why it's trying Groovy.

Should I try to use the "java" class and follow the example like in ServerSentEvents? It uses Embedded app and the form of a test, but I don't think a test is possible because there is no websockets client in Ratpack (that I know of).

**Comment by davidmc24** [comment]
@gillius Most likely JavaChainDslFixure was implemented before we had true support for Java-based fixtures.  I'm trying to implement a fix for that.

**Comment by davidmc24** [comment]
I've pushed what I believe should be a fix to the `JavaChainDslFixure` to `master`.

**Comment by gillius** [comment]
I've fixed up my commit and rebased/squashed. I can now run :ratpack-manual:test and it works. I had to remove a "chain instanceof ratpack.handling.Chain" check that I took as part of the MetricsWebsocketBroadcastHandler example and I assumed it was just there as "documentation" since it doesn't actually do anything.

I wasn't able to run the "check" task though, :ratpack-groovy:test fails 9 tests, all look like this:

```
ratpack.groovy.template.MarkupTemplatingSpec > can render template FAILED
    java.nio.file.FileSystemException: C:\Users\Gillius\AppData\Local\Temp\junit3235136203887959469\app\templates\foo.gt
pl: The process cannot access the file because it is being used by another process.
```

I tried making sure I didn't have any other processes or anything else funny going on and I tried the build multiple times, cleaning and deleting the Temp folders, and each time it was consistent.

This doesn't seem related to my PR, so I think it's good to go if ratpack-manual test runs fine?

**Comment by davidmc24** [comment]
If you wanted to preserve the `chain instanceof ...` line, you can do it like this:

https://github.com/ratpack/ratpack/commit/5aaa21f45e6e4b9405363276c096dc4fd5b8d304#diff-c13a198634c0731b08037a845cf639d6R36

**Comment by gillius** [comment]
OK I see that now... I was just following the example from the MetricsWebsocketBroadcastHandler. I'll do whatever the project members think is best here.

I see the Travis build failed but the error was an OutOfMemoryException after building for almost 50 minutes. I think what I did is good to go because I can run ratpack-groovy:test. Let me know if there is anything else you want me to add to the PR.

**Comment by alkemist** [comment]
Thanks for the contribution!

**Pull request merged**
