### PR TITLE
Provide means of registering async actions on promises.

### PR DESCRIPTION
**Pull request by johnrengelman**
[Review on Reviewable](https://reviewable.io/reviews/ratpack/ratpack/814)

### CODE REVIEW

**Comment by alkemist** [comment]
Review status: 0 of 2 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 345 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0Tc2CM5lPA8dgaf16y)** ([raw file](https://github.com/ratpack/ratpack/blob/c12c25dbc6764d852e21eaea82a5c5d95115e38c/ratpack-core/src/main/java/ratpack/exec/Promise.java#L345)):</sup>
Should move `@Deprecated` to be under the javadoc block. The `@deprecated` bit is around the wrong way. The replacement is the most important thing, followed by when it was deprecated.


---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 352 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0TcUltEOzkXC3J8kfX)** ([raw file](https://github.com/ratpack/ratpack/blob/c12c25dbc6764d852e21eaea82a5c5d95115e38c/ratpack-core/src/main/java/ratpack/exec/Promise.java#L352)):</sup>
And that it is only called with a value. It's not called on error. I'd remove this sentence and have something here that explains when you might want to use this (generally).


---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 368 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0TcqUcoOvFLWW4iNuQ)** ([raw file](https://github.com/ratpack/ratpack/blob/c12c25dbc6764d852e21eaea82a5c5d95115e38c/ratpack-core/src/main/java/ratpack/exec/Promise.java#L368)):</sup>
I think we can come up with a more realistic example, involving nested promises.


---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 386 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0Td1KaEFdcFPRNiBa_)** ([raw file](https://github.com/ratpack/ratpack/blob/c12c25dbc6764d852e21eaea82a5c5d95115e38c/ratpack-core/src/main/java/ratpack/exec/Promise.java#L386)):</sup>
Add a `@see #nextOp(Function)`


---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 390 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0Tcw7WwtrpdBSaYN9Y)** ([raw file](https://github.com/ratpack/ratpack/blob/c12c25dbc6764d852e21eaea82a5c5d95115e38c/ratpack-core/src/main/java/ratpack/exec/Promise.java#L390)):</sup>
Where possible, we should put method calls on individual lines for stacktrace clarity. I often forget this myself.


---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 414 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0TdB2ZZOkai6RKyT28)** ([raw file](https://github.com/ratpack/ratpack/blob/c12c25dbc6764d852e21eaea82a5c5d95115e38c/ratpack-core/src/main/java/ratpack/exec/Promise.java#L414)):</sup>
Ditto better example.


---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 432 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0Td8_g-WH8N5XDBOAr)** ([raw file](https://github.com/ratpack/ratpack/blob/c12c25dbc6764d852e21eaea82a5c5d95115e38c/ratpack-core/src/main/java/ratpack/exec/Promise.java#L432)):</sup>
`@see #next`


---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 445 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0TdHh0NMi5OvW75Ufv)** ([raw file](https://github.com/ratpack/ratpack/blob/c12c25dbc6764d852e21eaea82a5c5d95115e38c/ratpack-core/src/main/java/ratpack/exec/Promise.java#L445)):</sup>
Would be good to have a sentence indicating when this might be useful, and to explain what happens when there's an upstream failure.


---

<sup>**[ratpack-core/src/test/groovy/ratpack/exec/PromiseOperationsSpec.groovy, line 402 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0TdX2DShJweWBdUar1)** ([raw file](https://github.com/ratpack/ratpack/blob/c12c25dbc6764d852e21eaea82a5c5d95115e38c/ratpack-core/src/test/groovy/ratpack/exec/PromiseOperationsSpec.groovy#L402)):</sup>
Should collect the original value to prove it didn't get lost.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/814)

**Comment by alkemist** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/814)

**Comment by johnrengelman** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[ratpack-core/src/test/groovy/ratpack/exec/PromiseOperationsSpec.groovy, line 402 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0TdX2DShJweWBdUar1)** ([raw file](https://github.com/ratpack/ratpack/blob/c12c25dbc6764d852e21eaea82a5c5d95115e38c/ratpack-core/src/test/groovy/ratpack/exec/PromiseOperationsSpec.groovy#L402)):</sup>
There isn't a value here as we've called `operation()`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/814)

**Comment by alkemist** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 385 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0Uzwyhstc-PVDjKMO9)** ([raw file](https://github.com/ratpack/ratpack/blob/c3b8c32b012c5fd3978088b5893c0393f183aed0/ratpack-core/src/main/java/ratpack/exec/Promise.java#L385)):</sup>
I can't see a reason for the use of the latches.


---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 407 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0V-1wsksG_7XA2359N)** ([raw file](https://github.com/ratpack/ratpack/blob/c3b8c32b012c5fd3978088b5893c0393f183aed0/ratpack-core/src/main/java/ratpack/exec/Promise.java#L407)):</sup>
grammar is out.


---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 450 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0V-8L4zlwdndE0XkjS)** ([raw file](https://github.com/ratpack/ratpack/blob/c3b8c32b012c5fd3978088b5893c0393f183aed0/ratpack-core/src/main/java/ratpack/exec/Promise.java#L450)):</sup>
Don't need the latch.


---

<sup>**[ratpack-core/src/test/groovy/ratpack/exec/PromiseOperationsSpec.groovy, line 402 \[r1\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0TdX2DShJweWBdUar1)** ([raw file](https://github.com/ratpack/ratpack/blob/c12c25dbc6764d852e21eaea82a5c5d95115e38c/ratpack-core/src/test/groovy/ratpack/exec/PromiseOperationsSpec.groovy#L402)):</sup>
Can we please insert a capture of the value after `nextOp` then please.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/814)

**Comment by erdi** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 498 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0VictAILlCirWdq55t)** ([raw file](https://github.com/ratpack/ratpack/blob/c3b8c32b012c5fd3978088b5893c0393f183aed0/ratpack-core/src/main/java/ratpack/exec/Promise.java#L498)):</sup>
It would probably also be good to also add `default Operation replace (Operation next)`


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/814)

**Comment by johnrengelman** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 498 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0VictAILlCirWdq55t)** ([raw file](https://github.com/ratpack/ratpack/blob/c3b8c32b012c5fd3978088b5893c0393f183aed0/ratpack-core/src/main/java/ratpack/exec/Promise.java#L498)):</sup>
@alkemist thoughts on this?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/814)

**Comment by alkemist** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 498 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0VictAILlCirWdq55t)** ([raw file](https://github.com/ratpack/ratpack/blob/c3b8c32b012c5fd3978088b5893c0393f183aed0/ratpack-core/src/main/java/ratpack/exec/Promise.java#L498)):</sup>
We have to reconcile somehow with https://github.com/ratpack/ratpack/blob/master/ratpack-core/src/main/java/ratpack/exec/Operation.java#L102-102.

It's quite different for Operation, as there is no real value to replace, but we do have a bit of friction here.

If you squint, it does make sense to keep next() on Operation and add the method Marcin is suggesting.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/814)

**Comment by alkemist** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 376 \[r3\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0YMYPC5aMsQbM7MNla)** ([raw file](https://github.com/ratpack/ratpack/blob/e76588b5d27af8035d398ef569ad334747a1eb9c/ratpack-core/src/main/java/ratpack/exec/Promise.java#L376)):</sup>
.then(events::add)


---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 440 \[r3\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0YMoAJfVqcXUYxpqh5)** ([raw file](https://github.com/ratpack/ratpack/blob/e76588b5d27af8035d398ef569ad334747a1eb9c/ratpack-core/src/main/java/ratpack/exec/Promise.java#L440)):</sup>
events::add


---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 453 \[r3\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0YN6NQ1_HDbSTRQyu9)** ([raw file](https://github.com/ratpack/ratpack/blob/e76588b5d27af8035d398ef569ad334747a1eb9c/ratpack-core/src/main/java/ratpack/exec/Promise.java#L453)):</sup>
need to break up lines for stacktrace reasons


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/814)

**Comment by johnrengelman** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 498 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0VictAILlCirWdq55t)** ([raw file](https://github.com/ratpack/ratpack/blob/c3b8c32b012c5fd3978088b5893c0393f183aed0/ratpack-core/src/main/java/ratpack/exec/Promise.java#L498)):</sup>
I guess this doesn't make sense to me. The connotation here is that you are taking a promise and mapping it to an operation without consuming the promised value. If that's the case, then what's the purpose of chaining the `Operation` to this `Promise`?  Why not just have them separate. If the mapped `Operation` consumes the the promised value, then the `nextOp(Function<T, Operation>)` method should be used and the resulting promise can be mapped to an`Operation` by calling `.operation()`.

I do agree there is some friction in the API with deprecating `next(Promise)` in favor of `replace(Promise)` and not having the same method on `Operation`


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/814)

**Comment by johnrengelman** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 498 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0VictAILlCirWdq55t)** ([raw file](https://github.com/ratpack/ratpack/blob/c3b8c32b012c5fd3978088b5893c0393f183aed0/ratpack-core/src/main/java/ratpack/exec/Promise.java#L498)):</sup>
Just a thought, we could add `Operation consume(Function<T, Operation>)` to the `Promise` API and that would convey the purpose and intent.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/814)

**Comment by alkemist** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 498 \[r2\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0VictAILlCirWdq55t)** ([raw file](https://github.com/ratpack/ratpack/blob/c3b8c32b012c5fd3978088b5893c0393f183aed0/ratpack-core/src/main/java/ratpack/exec/Promise.java#L498)):</sup>
Let's push this issue out of scope. We can always add later. Resolving this.


---

<sup>**[ratpack-core/src/main/java/ratpack/exec/Promise.java, line 376 \[r3\]](https://reviewable.io:443/reviews/ratpack/ratpack/814#-K0YMYPC5aMsQbM7MNla)** ([raw file](https://github.com/ratpack/ratpack/blob/e76588b5d27af8035d398ef569ad334747a1eb9c/ratpack-core/src/main/java/ratpack/exec/Promise.java#L376)):</sup>
What was the resolution here? This is marked  as resolved with no comment or change.

Nevermind, I'll merge then fix up.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ratpack/ratpack/814)

**Comment by johnrengelman** [comment]
Whoops sorry. I forgot to push the changes. I'll get them in tonight.

**Comment by alkemist** [comment]
Don’t worry about it, I’ll do the touch ups.

**Pull request merged**
