### PR TITLE
Adds a general and extensible mechanism for externally imposed “overrides”

### PR DESCRIPTION
**Pull request by alkemist**
[Review on Reviewable](https://reviewable.io/reviews/ratpack/ratpack/858)

Proposed solution for #743 and #828.

### CODE REVIEW

**Comment by alkemist** [comment]
@ratpack/committers please take a look and let me know what you think. If we are happy with the direction, we can flesh out with docs and more tests.

**Comment by alkemist** [comment]
@johnrengelman I think we should close #857 and add that functionality to this branch, building on this mechanism. WDYT?

**Comment by johnrengelman** [comment]
Agreed. I closed the other PR in favor of this. Will take a further dive in a bit.

**Comment by alkemist** [comment]
@ratpack/committers ping.

**Comment by alkemist** [comment]
Superseded by #859.

**Pull request merged**
