### PR TITLE
metrics regex reporter filter

### PR DESCRIPTION
**Pull request by gschrader**
It would be nice to have the test also check the jmx reporter, the other tests aren't checking it currently so I'll see how hard it would be to add that.

### CODE REVIEW

**Comment by alkemist** [comment]
Hi @gschrader 

Looks like there are some build failures with this change.

**Comment by gschrader** [comment]
oops, sorry I will fix it

**Comment by rhart** [comment]
Thanks @gschrader, this is exactly what I was thinking.

@alkemist is the approach ok to you? Exposing the configurable options of the reporters on our config objects as opposed to just exposing the reporter builders?

**Comment by alkemist** [comment]
@rhart seems like a common bit of config, so +1 from me.

**Comment by alkemist** [comment]
didn't mean to close.

**Pull request merged**
